apiVersion: v1
kind: Service
metadata:
  name: coredns-dynapi-adapter
  labels:
    app: coredns-dynapi-adapter
spec:
  selector:
    app: coredns-dynapi-adapter
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
